/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-07-06 10:01:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.signup;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_005finput_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/signup_input.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/js/signup_input.js\"></script>\r\n");
      out.write("<head>\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Raleway:wght@600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>회원가입_정보 입력</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <div><h1>People in trip</h1></div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"signup_box\">\r\n");
      out.write("        <aside class=\"signup_leftside\">\r\n");
      out.write("            <div id=\"aside_box1\">정보입력</div>\r\n");
      out.write("            <div id=\"aside_box2\">가입완료</div>\r\n");
      out.write("        </aside>\r\n");
      out.write("        <section class=\"signup_main\" id=\"signup_input\">\r\n");
      out.write("            <div id=\"main_div1\">\r\n");
      out.write("                <table id=\"main_table1\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td id=\"main_head\">회원가입_정보입력</td>\r\n");
      out.write("                        <td id=\"main_head2\"> 전부 필수 작성사항입니다.</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"main_div2\">\r\n");
      out.write("                <form action=\"#\">\r\n");
      out.write("                    <table id=\"main_table2\" border=\"1\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"table2_td1\"><strong>아이디</strong></td>\r\n");
      out.write("                            <td class=\"table2_td2\">\r\n");
      out.write("                                <input type=\"text\" id=\"input_id\" name=\"input_id\"/><div id=\"hiddendiv_id\"></div></td>\r\n");
      out.write("                            <td class=\"table2_td3\">\r\n");
      out.write("                                <button class=\"t2_btn\" type=\"button\">중복<br/>확인</button>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td colspan=\"2\" class=\"table2_td4\">\r\n");
      out.write("                                <span>영문, 숫자를 조합하여 6~20자 <br/>이내로 입력하시오.<br/>\r\n");
      out.write("                                    (대소문자 구별x. 한글/특문 사용 불가)\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </td>\r\n");
      out.write("\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"table2_td1\"><strong>비밀번호</strong></td>\r\n");
      out.write("                            <td class=\"table2_td2\">\r\n");
      out.write("                                <input type=\"text\" id=\"input_pass\" name=\"input_pass\"/>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"table2_td3\" colspan=\"2\">\r\n");
      out.write("                                <span>영문, 숫자, 특수문자를 조합하여<br/> 8~20자 이내로 입력하시오.\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </td>\r\n");
      out.write("\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"table2_td1\" id=\"input_pass2\" name=\"input_pass2\"><strong>비밀번호 확인</strong></td>\r\n");
      out.write("                            <td class=\"table2_td2\">\r\n");
      out.write("                                <input type=\"text\"/>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"table2_td3\" colspan=\"2\"><div id=\"hiddendiv_pass2\"></div></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"table2_td1\"><strong>닉네임</strong></td>\r\n");
      out.write("                            <td class=\"table2_td2\">\r\n");
      out.write("                                <input type=\"text\" id=\"input_nick\" name=\"input_nick\"/><div id=\"hiddendiv_nick\"></div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"table2_td3\"><button class=\"t2_btn\" type=\"button\">중복<br/>확인</button></td>\r\n");
      out.write("                            <td colspan=\"2\" class=\"table2_td4\">\r\n");
      out.write("                                <span>영문, 숫자를 조합하여 6~20자 <br/>이내로 입력하시오.<br/>\r\n");
      out.write("                                    (대소문자 구별x. 한글/특문 사용 불가)\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr id=\"email_tr\">\r\n");
      out.write("                            <td class=\"table2_td1\"><strong>이메일</strong></td>\r\n");
      out.write("                            <td colspan=\"2\" id=\"table2_mtd2\">\r\n");
      out.write("                                <input class=\"mailinput\" id=\"mailinput1\" name=\"mailinput1\" type=\"text\"/> &nbsp;&nbsp; @\r\n");
      out.write("                                <div class=\"hiddendiv_email\">&nbsp;</div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td id=\"table2_mtd3\">\r\n");
      out.write("                                <select id=\"email_option\" name=\"email_option\">\r\n");
      out.write("                                    <option value=\"gmail\">gmail.com</option>\r\n");
      out.write("                                    <option value=\"naver\">naver.com</option>\r\n");
      out.write("                                    <option value=\"daum\">daum.net</option>\r\n");
      out.write("                                    <option value=\"direct\">직접입력</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                                <div class=\"hiddendiv_email\">&nbsp;</div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td id=\"table2_mtd4\">\r\n");
      out.write("                                <button class=\"t2_btn\" type=\"button\">이메일<br/>인증</button>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr id=\"last_tr\">\r\n");
      out.write("                            <td colspan=\"5\">\r\n");
      out.write("                                <button class=\"t2_btn\" id=\"submit_btn\" type=\"submit\">가입하기</button>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
